### PR TITLE
ELPP-3278 Draft of PHP major/minor versions ADR

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by lsh-0** [comment]
* I would err on **targeting whatever ships natively with the Ubuntu LTS release** and dropping third party PPAs. 
* Using PPAs should be the exception, not the rule.
* We should make more of an effort to upgrade to every LTS with backwards support for the previous LTS.
* 18.04 LTS is fast approaching, but no details yet on the version it will support
* Civi was brought kicking and screaming onto 14.04, works without too much hassle on 16.04 and [appears to support 7.0](https://docs.civicrm.org/sysadmin/en/latest/requirements/#php-version) (pinging @gnott )
* upgrading for new features/libraries argument is a `nicetohave`, upgrading to receive security fixes is a `musthave`.
* PHP doesn't seem to support it's releases for very long: http://php.net/supported-versions.php - 2 years of security support is not much.

**Comment by giorgiosironi** [comment]
Incorporating most of these points, waiting to hear from more people on 7.1, 7.2 upgrades.

**Comment by lsh-0** [comment]
gut feeling is the next LTS (18.04, 5 year support, 2023) will have to support 7.2 as it gets the most security support (until Nov 2020). No word yet. I'll see if I can't hunt down a newsfeed or something for ubuntu to subscribe to.

**Comment by thewilkybarkid** [comment]
> I would err on **targeting whatever ships natively with the Ubuntu LTS release** and dropping third party PPAs.

That should be its own ADR as it has implications (eg we couldn't start using Symfony 4, which requires PHP 7.1, and we're couldn't use the new LTS for Node (see ELPP-3253)).

**Comment by giorgiosironi** [comment]
Nothing set in stone yet, but this point risks to become moot as we try to move towards containers, with the distro and PHP version combination dictated [somewhere else](https://hub.docker.com/_/php/):

- `7.0-cli-jessie`
- `7.1-cli-jessie`
- `7.2-cli-stretch`

In that case, the distro is only used to execute the PHP processes, so there is typically less consistency across projects but more stability of the hosts as they can all run Ubuntu 14.04 or Ubuntu 16.04 without any PPA.

**Comment by giorgiosironi** [comment]
Updated by adding information for Docker images, since we now have basic `dev`-only container support for a PHP project: https://github.com/elifesciences/annotations/blob/develop/Dockerfile.cli

**Comment by giorgiosironi** [comment]
The current version leaves out whether the PHP version will be provided from a distribution, a PPA, or a Docker image. This will depend on a lot of factors when we actually need it, so out of scope for this.

Any objections to the current version before we try to push [ELPP-3278](https://elifesciences.atlassian.net/browse/ELPP-3278) ahead?

**Review by lsh-0 — APPROVED** [review]

**Review by thewilkybarkid — APPROVED** [review]

**Review by nlisgo — APPROVED** [review]
Great to have this document. It would be great to set a deadline by which we would like to move to 7.1 on all bit `crm`.

**Comment by giorgiosironi** [comment]
Hard deadline is before the end of 2018, but there are so many variables that it could be earlier.

**Pull request merged**
