### PR TITLE
Pushing responsibilities away from CiviCRM

### PR DESCRIPTION
**Pull request by giorgiosironi**
From the last retrospective.

### CODE REVIEW

**Comment by BlueReZZ** [comment]
I agree with all of that, makes a lot of sense and good to have the Civinky example there too.

**Review by BlueReZZ — APPROVED** [review]

**Comment by gnott** [comment]
If I understand the suggestion correctly, it is to create independent components that interacts with CiviCRM via its API, rather than developing any native CiviCRM extensions? As opposed to finding a wholesale replacement of CiviCRM?

**Comment by giorgiosironi** [comment]
> create independent components that interacts with CiviCRM via its API, rather than developing any native CiviCRM extensions? 

There are two scenarios: CiviCRM calling something and something calling CiviCRM. In both cases a extension may be necessary (respectively to integrate internal events with an external API, or to expose a basic API for that service to call). What we say here is to keep the extension as minimal as possible and push all the logic to other services that sit on firmer ground.

> As opposed to finding a wholesale replacement of CiviCRM?

That would be not just a tech team decision, would involve multiple teams for sure.

**Review by lsh-0 — APPROVED** [review]

**Review by gnott — APPROVED** [review]

**Review by thewilkybarkid — APPROVED** [review]
👍 👍 👍

**Comment by giorgiosironi** [comment]
@sianroderick to put this into practice, when can this team be involved in an architectural review of the next steps of eToc? I've heard about extensions like customized newsletters

**Comment by sianroderick** [comment]
@giorgiosironi There's a meeting set-up on 26 Jan to talk about the next steps (personalisation).

**Pull request merged**
